jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Fish\UserBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: true
            iterations: 2

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            id: fish.user.provider
            #entity: { class: FishUserBundle:User, property: username }

    firewalls:
        public_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                failure_handler: fish.user.blacklist.service
                success_handler: fish.user.blacklist.service
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
